version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springboot_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container

    ports:
      - "8080:8080"
    depends_on:
      - mysql


volumes:
  mysql-data:
